### ISSUE TITLE
Error in finding config.in

### ISSUE THREAD

**Issue by lee1043** [PCMDI/ARMP#8]
```
$ python driver_AR.py 
```

Error message:
```
Traceback (most recent call last):
  File "/Users/lee1043/Documents/Research/git/ARMP/ARMP/driver_AR.py", line 1, in <module>
    from driver_clim import run_ARMP_clim
  File "/Users/lee1043/Documents/Research/git/ARMP/ARMP/driver_clim.py", line 1, in <module>
    from ARMP.app.clim_analysis import Clim_analysis
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/ARMP/__init__.py", line 1, in <module>
    from ARMP.io.printting import print_armp
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/ARMP/io/printting.py", line 3, in <module>
    from ARMP.lib.loader import dic
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/ARMP/lib/loader.py", line 16, in <module>
    with open(config_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/ARMP/params/config.in'
```

Instead of finding `config.in` from relative local path (`./params/config.in`), it is trying to find the file from env where the package is installed (`/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/ARMP/params/config.in`).

**Comment by bosup** [comment]
fixed using Package Location method

**Comment by bosup** [comment]
include config.in file in setup.py
